server:
  port: ${PORT}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    locations: classpath:db/migration

  jpa:
    open-in-view: true

logging:
  file:
    name: log/offices.log
  pattern:
    file: "%level | %logger | %msg | %X{id} %X{username} %X{attribute}%n"
    console: "%level | %logger | %msg | %X{id} %X{username} %X{attribute}%n"
  level:
    by.shimakser.currencies: debug
    root: info