version: '3.3'
services:
  postgres:
    container_name: postgresdb
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ManagingAd
    restart: always

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_DB: ManagingAd
      MONGO_HOST: mongodb
    depends_on:
      - postgres
    restart: always

  app:
    container_name: managingad
    image: springboot-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo