FROM openjdk:11 as builder
COPY . /ManagingAd
WORKDIR /ManagingAd
RUN chmod +x mvnw && ./mvnw package -DskipTests

FROM openjdk:11
ENV JAR_FILE_NAME="dictionary.jar"
EXPOSE 8084
RUN mkdir /dictionary
COPY --from=builder ManagingAd/services/dictionary/target/$JAR_FILE_NAME /dictionary/$JAR_FILE_NAME
ENTRYPOINT ["java", "-jar","/dictionary/dictionary.jar"]
