server:
  port: 8084

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${DB}

  cache:
    type: redis

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

mongock:
  change-logs-scan-package: by.shimakser.redis.config
