server:
  port: ${PORT}
  servlet:
    context-path: /managingad
  ssl:
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2
    key-store-type: PKCS12
    key-store: classpath:keystore/Server-keystore.p12
    key-store-password: password
    client-auth: need
    trust-store-type: PKCS12
    trust-store: classpath:keystore/Server-truststore.p12
    trust-store-password: password

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    locations: classpath:db/migration

  jpa:
    open-in-view: true

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${DB}

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    topic:
      registration-topic: registration-topic
      request-topic: request-topic
      requestreply-topic: requestreply-topic
    consumer:
      registration-group: registration-group
      requestreply-group: requestreply-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: by.shimakser.dto;
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cache:
    collection-name: Currency
    cache-name: currency

feign:
  application-url: ${CURRENCIES_HOST}:${CURRENCIES_PORT}/currencies