server:
  port: ${PORT}
  servlet:
    context-path: /managingad

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    locations: classpath:db/migration

  jpa:
    open-in-view: true

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${DB}

  cache:
    collection-name: Currency
    cache-name: currency

feign:
  application-url: ${CURRENCIES_HOST}:${CURRENCIES_PORT}/currencies