name: Build-application-services

on:
  push:
    branches: [ dev-shiyanov-training ]
  pull_request:
    branches: [ dev-shiyanov-training ]

  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v1 
      - name: Package services
        run: mvn package
