name: Pre-release

on:
  push:
    branches: [ dev-shiyanov-training ]
  pull_request:
    branches: [ dev-shiyanov-training ]

  workflow_dispatch:

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v1
      - name: Set up JDK 11      
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Package services
        run: mvn package
      - name: Pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.jar
